# DO NOT CHANGE the "init" and "install" sections below

# Change SilentlyContinue to Stop for production (Graeme)
# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "SilentlyContinue"
        Invoke-WebRequest http://raw.github.com/nfultz/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Adapt as necessary starting from here
environment:
  GH_TOKEN:
    secure: U28+gCBG1Cvf5yMApAHJsKgECKfemz0N3I8Gx8vrfIzHUZyag8AWs/tzZawj9gzH

  matrix:
  - R_VERSION: release

  - R_VERSION: oldrel
    RTOOLS_VERSION: 33

build_script:
  - travis-tool.sh install_deps
  - travis-tool.sh install_github DeclareDesign/DDtools
  - travis-tool.sh install_github DeclareDesign/fabricatr@v0.4.0

test_script:
  - travis-tool.sh run_tests

on_success:
  - Rscript -e DDtools::after_build

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
